### ISSUE TITLE
Now that this is owned by Automattic, could we get some non-hideous docs?

### ISSUE THREAD

**Issue by corysimmons** [Automattic/stylus#1870]
It's really an embarrassment to what an amazing tool Stylus is.

I've built some unofficial docs (I wouldn't mind you linking to): http://stylus-lang.com

But if that's not your cup of :tea: then could Automattic put a few workers on designing something that's clean and responsive?

**Comment by corysimmons** [comment]
Also, I wouldn't mind transferring this repo to you guys at any time.

**Comment by kizu** [comment]
I'm currently in process of talking with them about all that stuff, I'll post in that issue any news about it.

**Comment by corysimmons** [comment]
Big :+1:

**Comment by kizu** [comment]
Hey, @corysimmons! :)

We managed to get `stylus` organization and moved stylus there, so, ta-da: https://github.com/stylus/stylus :boom:

Also: I talked with them about your site and logo, and they are all in excepts for some minor issues, I'll quote the initial response:

> - I think it's much better (both logo and site)
> - I think the redirection is a great idea. 
> - I think a mention on http://stylus-lang.com/ as having originated at LearnBoost and created by TJ Holowaychuk in the footer makes sense.
> - I think they should explicitly release the logo to the public domain before the transfer happens.

Then a bit more about the logo:

> This portion of the type looks weird to me
> https://cloudup.com/cmoUswOv6lZ
> (the connection between the t and the y)

And, of course, we should mention Automattic at the bottom, I'll cite:

> I think it's important to make a distinction between the "supporting" organizations and the originating organization.
> On the sidebar, it'd also be appropriate to add Automattic's logo: (you can find it here: http://automattic.com/press/)

[Here is a direct link to pdf of the logo that should be used](https://automattic.files.wordpress.com/2005/12/automattic-cmyk.pdf)

I think we should place all the logos in the sidebar like this:

1. At the first line there should be something like “Originated at LearnBoost and created by TJ Holowaychuk”
2. Then “supported by” and Automattic, Launchbox and mojotech logos.

- - -

Also, I think you could already transfer the repo for the stylus-lang.com to stylus org, I'll then create a Team for working on this repo and would add you (and anyone who you'd say would work on the site) to it as members, we'd work a bit on the site (there are some things to do like replace the links to stylus repo, the mentioned before changes to sidebar, etc.)

I guess I'll save for now all the design you've done there, then look at the engine: I remember that you didn't used the submodule for getting the actual docs from the repo? I could do all the Jekyll changes so the site would work the same as the current docs.

So, let's get things moving? :) If you'll have any more questions, I'll happily answer them!

**Comment by futekov** [comment]
I'll happily contribute if any help is needed.

**Comment by corysimmons** [comment]
@futekov The site is on Github at https://github.com/LaunchBoxHQ/stylus-lang.com if you want to contribute.

**Comment by corysimmons** [comment]
@kizu Huge/exciting news! I'll have to check with MojoTech if they're willing to release the logo to public domain in exchange for their link on the site but I don't think it would be a problem.

I'll go ahead and transfer the site to Stylus org. I can transfer the domain at anytime as well.

You'll definitely need to implement a better system for submoduling the docs and such. Mine solution was slapped together in a few minutes.

I don't have anyone else I'd be adding to the repo.

@futekov Once I transfer it over I'll ping you, and you can start implementing all the changes they're asking for.

**Comment by corysimmons** [comment]
@kizu Apparently I need Stylus org admin rights to transfer a repo over to Stylus org.

**Comment by kizu** [comment]
@corysimmons Created a team with the admin rights for the site, send an invite to you.

**Comment by corysimmons** [comment]
@kizu Transferred repo.

@futekov https://github.com/stylus/stylus-lang.com feel free to jump in and address the issues Roman mentioned above.

**Comment by futekov** [comment]
@corysimmons :+1: Will start working on that later today
