### ISSUE TITLE
Comunity Speed Test

### ISSUE THREAD

**Issue by Sinius15** [Automattic/stylus#1871]
Dear Stylus Community,

I am a computer-science student in Holland and i am doing research on css-preprocessors. One of the aspects i am interested in is the community support. This is a test to discover the reaction speed of the community to issues. I will measure the time it takes to close this issue. 
Would the first person who reads this please close this issue?

Thanks in advance!

**Comment by kizu** [comment]
:)

**Comment by Sinius15** [comment]
@kizu Thanks! You are the second to respond. Congratulations!

**Comment by vendethiel** [comment]
(I couldn't close it, so I didn't answer this :P)
